jobhelpers.c: Check the value of the assigned
Error: REVERSE_INULL (CWE-476): [#def15]
udisks-2.7.1/modules/lvm2/jobhelpers.c:282: deref_ptr: Directly
    dereferencing pointer "ret".
udisks-2.7.1/modules/lvm2/jobhelpers.c:283: check_after_deref: Null-checking
    "ret" suggests that it may be null, but it has already been dereferenced
    on all paths leading to the check.

Signed-off-by: Tony Asleson <tasleson@redhat.com>