tests: Remove resolve_device tests involving partition creation
This is a partial revert of commit cf47eeeae1 that depends on full
object update after partitioning. That is still work in progress
(see #955) and prone to race conditions.

  ======================================================================
  FAIL: test_60_resolve_device (test_10_basic.UdisksBaseTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/jenkins/workspace/udisks-pr/arch/x86_64/distro/centos_9s/type/udisks/src/tests/dbus-tests/test_10_basic.py", line 335, in test_60_resolve_device
      self.assertEquals(part_name_val, part_label)
  AssertionError: dbus.String('', variant_level=1) != 'PRTLBLX'