udisksiscsiutil.c: Correct strncpy lengths
The ISCSI constants are the size of the variable, thus you must leave at
lease 1 character free for the terminating character.

Error: BUFFER_SIZE_WARNING (CWE-120): [#def6]
udisks-2.7.1/modules/iscsi/udisksiscsiutil.c:139: buffer_size_warning: Calling
strncpy with a maximum size argument of 256 bytes on destination array
"(*auth_info).chap.username" of size 256 bytes might leave the destination
string unterminated.

Error: BUFFER_SIZE_WARNING (CWE-120): [#def11]
udisks-2.7.1/modules/iscsi/udisksiscsiutil.c:168: buffer_size_warning: Calling
strncpy with a maximum size argument of 1025 bytes on destination array
"node->address" of size 1025 bytes might leave the destination string unterminated.

Signed-off-by: Tony Asleson <tasleson@redhat.com>