udiskslinuxiscsisessionobject.c: Correct precondition check
The macro g_return_val_if_fail expects the test to be true otherwise it
returns the second parameter.  Thus we want the device to != NULL and we
want it also be a linux device.  This is because we dereference device in
the function, it cannot be NULL.

Error: CLANG_WARNING: [#def13]
udisks-2.7.1/modules/iscsi/udiskslinuxiscsisessionobject.c:406:46: warning: Access to field 'udev_device'
results in a dereference of a null pointer (loaded from variable 'device')
udisks-2.7.1/modules/iscsi/udiskslinuxiscsisessionobject.c:403:25: note: Assuming 'device' is equal to null
/usr/include/glib-2.0/glib/gmessages.h:586:18: note: expanded from macro 'g_return_val_if_fail'
/usr/include/glib-2.0/glib/gmacros.h:376:60: note: expanded from macro 'G_LIKELY'
/usr/include/glib-2.0/glib/gmacros.h:370:8: note: expanded from macro '_G_BOOLEAN_EXPR'
udisks-2.7.1/modules/iscsi/udiskslinuxiscsisessionobject.c:403:40: note: Left side of '||' is true
udisks-2.7.1/modules/iscsi/udiskslinuxiscsisessionobject.c:403:3: note: Taking true branch
/usr/include/glib-2.0/glib/gmessages.h:586:6: note: expanded from macro 'g_return_val_if_fail'
udisks-2.7.1/modules/iscsi/udiskslinuxiscsisessionobject.c:403:3: note: Loop condition is false.  Exiting loop
/usr/include/glib-2.0/glib/gmessages.h:585:40: note: expanded from macro 'g_return_val_if_fail'
/usr/include/glib-2.0/glib/gmacros.h:337:23: note: expanded from macro 'G_STMT_START'
udisks-2.7.1/modules/iscsi/udiskslinuxiscsisessionobject.c:406:46: note: Access to field 'udev_device'
results in a dereference of a null pointer (loaded from variable 'device')

Signed-off-by: Tony Asleson <tasleson@redhat.com>