integration-test: Sleep for a while after mdraid creation
Integration tests are missing synchronization mechanisms and waiting
for an object to appear on the bus. Thus for now, add a nasty sleep.

  ======================================================================
  FAIL: test_md_raid_methods (__main__.MDRaid.test_md_raid_methods)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/tbzatek/devel/udisks/src/tests/integration-test", line 1855, in test_md_raid_methods
      self.assertIsNotNone(block)
      ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  AssertionError: unexpectedly None